// Generated by CoffeeScript 1.6.3
(function() {
  exports.calculateRatio = function(times) {
    var i, inside, outside, x, y, _i;
    inside = [];
    outside = [];
    for (i = _i = 1; 1 <= times ? _i <= times : _i >= times; i = 1 <= times ? ++_i : --_i) {
      x = Math.random();
      y = Math.random();
      if (Math.sqrt((Math.pow(x, 2)) + (Math.pow(y, 2)) <= 1)) {
        inside.push([x, y]);
      } else {
        outside.push([x, y]);
      }
    }
    return inside.length / times;
  };

}).call(this);
